//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requirement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Recruitment_DBEntities : DbContext
    {
        public Recruitment_DBEntities()
            : base("name=Recruitment_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<mst_AboutPosition> mst_AboutPosition { get; set; }
        public virtual DbSet<mst_Advertisement> mst_Advertisement { get; set; }
        public virtual DbSet<mst_Designation> mst_Designation { get; set; }
        public virtual DbSet<mst_District> mst_District { get; set; }
        public virtual DbSet<mst_EmpCode> mst_EmpCode { get; set; }
        public virtual DbSet<mst_Location> mst_Location { get; set; }
        public virtual DbSet<mst_Name> mst_Name { get; set; }
        public virtual DbSet<mst_State> mst_State { get; set; }
        public virtual DbSet<mst_Theme> mst_Theme { get; set; }
        public virtual DbSet<tbl_NewHireMultiple_old> tbl_NewHireMultiple_old { get; set; }
        public virtual DbSet<tbl_NewHireMultipleCost> tbl_NewHireMultipleCost { get; set; }
        public virtual DbSet<tbl_NewHireStatus> tbl_NewHireStatus { get; set; }
        public virtual DbSet<tbl_Signature> tbl_Signature { get; set; }
        public virtual DbSet<mst_Applicable> mst_Applicable { get; set; }
        public virtual DbSet<mst_CostCentreCode> mst_CostCentreCode { get; set; }
        public virtual DbSet<mst_Grade> mst_Grade { get; set; }
        public virtual DbSet<mst_HiringType> mst_HiringType { get; set; }
        public virtual DbSet<mst_JobLocation> mst_JobLocation { get; set; }
        public virtual DbSet<mst_Position> mst_Position { get; set; }
        public virtual DbSet<mst_Sal> mst_Sal { get; set; }
        public virtual DbSet<mst_SelectionProcess> mst_SelectionProcess { get; set; }
        public virtual DbSet<mst_TypeYesNo> mst_TypeYesNo { get; set; }
        public virtual DbSet<mst_KeyRole> mst_KeyRole { get; set; }
        public virtual DbSet<mst_SelectionInterview> mst_SelectionInterview { get; set; }
        public virtual DbSet<mst_TypeofInterview> mst_TypeofInterview { get; set; }
        public virtual DbSet<tbl_JobDAbout> tbl_JobDAbout { get; set; }
        public virtual DbSet<Tbl_JobDKeyRole> Tbl_JobDKeyRole { get; set; }
        public virtual DbSet<tbl_JobD> tbl_JobD { get; set; }
        public virtual DbSet<mst_ProjectMaster> mst_ProjectMaster { get; set; }
        public virtual DbSet<tbl_NewHire> tbl_NewHire { get; set; }
    }
}
