//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requirement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NewHireStatus
    {
        public int NewHireStatusId_pk { get; set; }
        public Nullable<System.Guid> NewHireId_fk { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> LevelStatusId { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<bool> ApprovedStatus { get; set; }
        public string ApprovedRemark { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
    }
}
