//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requirement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NewHire
    {
        public int Id_pk { get; set; }
        public System.Guid Emp_Id { get; set; }
        public Nullable<System.DateTime> NewHiredDate { get; set; }
        public Nullable<int> HiringType_Id { get; set; }
        public string PositionName { get; set; }
        public string ProjectName { get; set; }
        public string Location { get; set; }
        public Nullable<int> TypeofApplicable_Id { get; set; }
        public Nullable<int> NoofPositions_Id { get; set; }
        public Nullable<int> jobLocationType_Id { get; set; }
        public string Remarks { get; set; }
        public string ReportingManager { get; set; }
        public Nullable<System.DateTime> Durationoftheposition_Fdate { get; set; }
        public Nullable<System.DateTime> Durationoftheposition_Tdate { get; set; }
        public Nullable<int> CostCentreCode_Id { get; set; }
        public Nullable<int> BaseSalRangepermonth_Id { get; set; }
        public Nullable<int> Grade_Id { get; set; }
        public Nullable<int> JD_Availability_Id { get; set; }
        public string JD_AvailabilityIfYes_Doc { get; set; }
        public Nullable<int> Advertisement_Id { get; set; }
        public Nullable<int> EmpaneledHead_Id { get; set; }
        public string InterviewPanel { get; set; }
        public Nullable<int> SelectionProcess_Id { get; set; }
        public Nullable<int> LaptopwithSpecifications_Id { get; set; }
        public string Anyspecificsoftwarewithlicense { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> IsDeletedOn { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> TypeOfInterview { get; set; }
        public string InterviewPanel2 { get; set; }
    }
}
